---
- name: Create Airsonic Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ airsonic_data_directory }}/data"
    - "{{ airsonic_data_directory }}/playlists"

- name: Airsonic Docker Container
  docker_container:
    name: airsonic
    image: linuxserver/airsonic
    pull: true
    volumes:
      - "{{ airsonic_data_directory }}/data:/config:rw"
      - "{{ airsonic_data_directory }}/playlists:/playlists:rw"
      - "{{ airsonic_music_directory }}:/music:rw"
      - "{{ airsonic_podcasts_directory }}:/podcasts:rw"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Berlin"
    ports:
      - "{{ airsonic_port }}:4040"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "airsonic"
      traefik.frontend.rule: "Host:{{ airsonic_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ airsonic_available_externally }}"
      traefik.port: "4040"

