---
- name: Create DDNS Data Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ddns_data_directory }}"

- name: Generate config.json
  copy:
    content: "{{ ddns_config | to_nice_json }}"
    dest: "{{ ddns_data_directory }}/config.json"

- name: Dynamic DNS Container
  docker_container:
    name: ddns-updater
    image: qmcgaw/ddns-updater:latest
    pull: true
    ports:
      - "{{ ddns_port }}:8000"
    volumes:
      - "{{ ddns_data_directory }}:/updater/data:rw"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    user: "0"

