---
- name: Create Nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nextcloud_data_directory }}/nextcloud"
    - "{{ nextcloud_data_directory }}/mysql"
    - "{{ nextcloud_data_directory }}/elasticsearch"

- name: Ensure elasticsearch directory permissions are correct
  command: chmod g+rwx {{ nextcloud_data_directory }}/elasticsearch

# dont know if needed
- name: Ensure elasticsearch directory permissions are correct
  command: chgrp 0 {{ nextcloud_data_directory }}/elasticsearch

- name: Nextcloud Mysql Docker Container
  docker_container:
    name: nextcloud-mysql
    image: mariadb:10.5.8-focal
    pull: true
    volumes:
      - "{{ nextcloud_data_directory }}/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud-user"
      MYSQL_PASSWORD: "nextcloud-pass"
      MYSQL_ROOT_PASSWORD: "nextcloud-secret"
    restart_policy: unless-stopped
    memory: 1g

- name: increase max map count for elasticsearch
  shell: sysctl -w vm.max_map_count=262144

- name: Nextcloud elasticsearch Docker Container
  docker_container:
    name: nextcloud-elasticsearch
    image: elasticsearch-ingest-attachment-arm64:latest
    pull: false
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1-arm64
    #pull: true
    volumes:
      - "{{ nextcloud_data_directory }}/elasticsearch:/usr/share/elasticsearch/data:rw"
    env:
      node.name: elastic01
      cluster.name: ncsearch
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      network.host: "0.0.0.0"
    restart_policy: unless-stopped
    ulimits:
      - 'memlock:-1:-1'
    ports:
      - "9200:9200"

- name: Nextcloud Docker Container
  docker_container:
    name: nextcloud
    image: nextcloud:20
    pull: true
    links:
        - nextcloud-mysql:mysql
        - nextcloud-elasticsearch:elasticsearch
    volumes:
      - "{{ nextcloud_data_directory }}/nextcloud:/var/www/html:rw"
    ports:
      - "{{ nextcloud_port }}:80"
    env:
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud-user"
      MYSQL_PASSWORD: "nextcloud-pass"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.{{ ansible_nas_domain }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "nextcloud"
      traefik.frontend.rule: "Host:{{ nextcloud_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ nextcloud_available_externally }}"
      traefik.port: "80"