---
- name: Create pyLoad Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ pyload_config_directory }}"
    - "{{ pyload_download_directory }}"

- name: pyLoad Docker Container
  docker_container:
    name: pyload
    image: pyload-custom
    #pull: true
    volumes:
      - "{{ pyload_config_directory }}:/config:rw"
      - "{{ pyload_download_directory }}:/downloads:rw"
    ports:
      - "{{ pyload_port }}:8000"
      - "7227:7227"
      - "9666:9666"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ pyload_user_id }}"
      PGID: "{{ pyload_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "pyload"
      traefik.frontend.rule: "Host:{{ pyload_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ pyload_available_externally }}"
      traefik.port: "8000"
