---
- name: Create ansible-nas group
  group:
    name: ansible-nas
    state: present
  register: g_result

- name: remember group id
  set_fact:
    ansible_nas_group_id: "{{ g_result.gid }}"

- name: Create ansible-nas user
  user:
    name: ansible-nas
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: ansible-nas
    shell: /usr/sbin/nologin
  register: u_result

- name: remember user id
  set_fact:
    ansible_nas_user_id: "{{ u_result.uid }}"