---
- name: Watchtower Docker Container
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      WATCHTOWER_NOTIFICATIONS: "gotify"
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: "https://gotify.wilden.cc/"
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "ANGovpK.SnRzL7c"
    command: "{{ watchtower_command }}"
    restart_policy: unless-stopped
    memory: 1g